bctip/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib.sitemaps.views import sitemap
from django.contrib.sitemaps import Sitemap
from django.contrib import admin
from django.conf import settings
admin.autodiscover()

urlpatterns = i18n_patterns('',
    url(r'^$', 'core.views.home', name='home'),
    url(r'^new/$', 'core.views.new', name='new'),
    url(r'^statistics/$', 'core.views.statistics', name='statistics'),
    url(r'^(?P<key>\w+-\w+-\w+-\w+-\w+)$', 'core.views.tip_redir'),
    url(r'^(?P<key>\w+-\w+-\w+-\w+-\w+)/$', 'core.views.tip'),
    url(r'^(?P<key>\w+-\w+-\w+)$', 'core.views.tip_redir', name='tip_redir'),
    url(r'^(?P<key>\w+-\w+-\w+)/$', 'core.views.tip', name='tip'),
    url(r'^gratuity-example/$', 'core.views.tips_example', name='tips_example'),
    url(r'^w/(?P<key>\w+)/$', 'core.views.wallet', name='wallet'),
    url(r'^w/(?P<key>\w+)/comments/$', 'core.views.comments', name='comments'),
    url(r'^w/(?P<key>\w+)/wajax/$', 'core.views.wajax', name='wajax'),
    url(r'^w/(?P<key>\w+)/print/$', 'core.views.printHTML', name='printHTML'),
)

urlpatterns += patterns('',
    #url(r'^admin/', include(admin.site.urls)),
    url(r'qrcode/(?P<key>\w+)/$','core.views.qrcode_view', name='qrcode'),
)

if settings.BCTIP_MOD:
    import bctip.urls_custom
urlpatterns += bctip.urls_custom.urlpatterns

core/models.py
# -*- coding: utf-8 -*-

import json
import urllib2
from decimal import Decimal

from django.conf import settings
from django.core.cache import cache
from django.db import models
from django.utils.translation import ugettext as _
from jsonrpc import ServiceProxy

BITCOIND = ServiceProxy(settings.BITCOIND_CONNECTION_STRING)
"""
access.getbalance()
access.getinfo()
settxfee(0.00001)
a.listaccounts()
a.listtransactions(acc)
"""
# 1 usd in rub
CURRENCY_RATES = {'USD': 1, 'EUR': 0.85, 'GBP': 0.75, 'SEK': 8.5, 'RUB': 60.0}
CURRENCY_SIGNS = {'USD': '$', 'EUR': '€', 'GBP': '£', 'SEK': 'kr'}
MESSAGES = {}
THANKS_MESSAGE = _("Thank you for your service!")
# Translators: Please provide youtube video about bitcoin in your language
LOCALIZED_YOUTUBE_URL = _("www.youtube.com/embed/Gc2en3nHxA4")


class Wallet(models.Model):
    key = models.CharField(max_length=64)  # secret
    ctime = models.DateTimeField(auto_now_add=True)
    # activation time (paid)
    atime = models.DateTimeField(null=True, blank=True)
    ip = models.IPAddressField(null=True, blank=True)
    ua = models.CharField(max_length=255, null=True, blank=True)
    bcaddr = models.CharField(max_length=90)  # pay to
    bcaddr_from = models.CharField(
        max_length=90, null=True, blank=True)  # paid from
    # target country: AU, US, RU. none for universal
    audience = models.CharField(max_length=2, null=True, blank=True)
    # amount of every tip, ex.:$2
    divide_by = models.DecimalField(
        decimal_places=8, max_digits=16, blank=True, null=True, default=0)
    divide_currency = models.CharField(
        max_length=3, default="USD")  # iso currency code
    quantity = models.SmallIntegerField(
        blank=True, null=True)  # how many
    template = models.CharField(
        max_length=34, default="001-original.odt")
    template_back = models.CharField(max_length=34, default="0000-default.odt")
    target_language = models.CharField(max_length=3, default="en")
    # custom message
    message = models.CharField(max_length=128, null=True, blank=True)
    # donation fee in percents
    price = models.DecimalField(decimal_places=2, max_digits=5, default="0")
    # tags for statistics
    hashtag = models.CharField(max_length=40, null=True, blank=True)
    # order print and post?
    print_and_post = models.BooleanField(default=False)
    # price of 1 BTC in target currency on this date
    rate = models.DecimalField(
        decimal_places=2, max_digits=10, blank=True, null=True, default=0)
    balance = models.BigIntegerField(null=True, blank=True)
    invoice = models.BigIntegerField(null=True, blank=True)
    activated = models.BooleanField(default=False)
    # expiration in days
    expiration = models.IntegerField(null=True, blank=True)
    src_site = models.SmallIntegerField(
        blank=True, null=True, default=0)  # for custom
    email = models.CharField(max_length=64, null=True, blank=True)
    fee = models.DecimalField(
        decimal_places=8, max_digits=10, blank=True, null=True)

    @property
    def balance_nbtc(self):
        return self.balance / 100.0  # 1e3

    @property
    def balance_mbtc(self):
        return self.balance / 100000.0  # 1e5

    @property
    def balance_btc(self):
        if self.balance:
            return self.balance/100000000.0 or None  # 1e8
        else:
            return None

    @property
    def fee_float(self):
        if self.fee:
            return float(self.fee)
        else:
            return 0.00001

    @property
    def txfee_float(self):
        return round(self.fee_float*3, 6)

    @property
    def invoice_btc(self):
        if self.invoice != None:
            return self.invoice / 100000000.0  # 1e8
        else:
            return None

    @property
    def bcaddr_uri(self):
        return "bitcoin:%s?amount=%s&label=bctip.org" % (
            self.bcaddr, self.invoice_btc)

    @property
    def divide_currency_sign(self):
        return CURRENCY_SIGNS[self.divide_currency]

    def __unicode__(self):
        return u"%s" % (self.key)

    def get_absolute_url(self):
        return u"/w/%s/" % self.key

    def get_account(self):
        return "%s_%s" % (self.id, self.key[-6:])

    def activated_tips(self):
        return Tip.objects.filter(wallet=self, activated=True).count()

    @property
    def rate_fiat(self):
        return int(self.rate * Decimal(CURRENCY_RATES[self.divide_currency]))


class Address(models.Model):
    wallet = models.ForeignKey(Wallet)
    country = models.CharField(max_length=64, default="USA")
    state = models.CharField(max_length=64, null=True, blank=True)
    address1 = models.CharField("Address line 1", max_length=64)
    address2 = models.CharField(
        "Address line 2", max_length=64, null=True, blank=True)
    city = models.CharField(max_length=64, blank=False)
    postal_code = models.CharField("Postal Code", max_length=32)

    def __unicode__(self):
        return u"%s" % (self.country, self.city, self.address1)

    def get_absolute_url(self):
        return u"/admin/core/address/%d/" % self.id


class Tip(models.Model):
    wallet = models.ForeignKey(
        Wallet, null=True, blank=True)
    key = models.CharField(max_length=64, null=True, blank=True)
    ctime = models.DateTimeField(
        auto_now_add=True, null=True, blank=True)
    # activation
    atime = models.DateTimeField(null=True, blank=True)
    # expiration
    etime = models.DateTimeField(null=True, blank=True)
    ip = models.IPAddressField(null=True, blank=True)  # пока не исп
    ua = models.CharField(max_length=255, null=True, blank=True)  # user agent
    balance = models.BigIntegerField(
        blank=True, null=True, default=0)
    miniid = models.CharField(max_length=4)
    comment = models.CharField(max_length=40, default="")
    comment_time = models.DateTimeField(null=True, blank=True)
    activated = models.BooleanField(default=False)
    expired = models.BooleanField(default=False)
    bcaddr = models.CharField(max_length=90, null=True, blank=True)
    txid = models.CharField(max_length=64, null=True, blank=True)
    # tip page visit counter
    times = models.IntegerField(null=True, blank=True, default=0)

    def __unicode__(self):
        return u"%s: %s" % (self.wallet, self.balance_btc)

    def get_absolute_url(self):
        domain = "https://www.bctip.org"
        return "%s/%s/" % (domain, self.key)

    @property
    def balance_nbtc(self):
        return self.balance / 100.0  # 1e3

    @property
    def balance_mbtc(self):
        return self.balance / 100000.0  # 1e5

    @property
    def balance_btc(self):
        return self.balance / 100000000.0  # 1e8

    @property
    def balance_usd(self):
        return round(self.balance_btc * get_avg_rate(), 2)

    @property
    def balance_eur(self):
        return round(self.balance_btc * get_avg_rate_euro(), 2)

    @property
    def balance_fiat(self):
        fiat = Decimal(self.balance_usd) * \
            Decimal(CURRENCY_RATES[self.wallet.divide_currency])
        return round(fiat, 2)


def get_avg_rate():
    rate = get_bitstamp_avg_rate()
    if rate:
        return rate
    rate = get_coinbase_avg_rate()
    if rate:
        return rate

    return 770.0  # if everything failed


def get_avg_rate_euro():
    rate = get_avg_rate()
    return int(rate*CURRENCY_RATES['EUR'])

"""
def get_mtgox_avg_rate():
    try:
        mtgox = urllib2.urlopen("https://data.mtgox.com/api/1/BTCUSD/ticker", timeout=5).read()
        mtgox = json.loads(mtgox)
        return float(mtgox['return']['avg']['value'])
    except:
        return None
"""


def get_btce_avg_rate(force=False):
    key = 'avg_rate_btce'
    rate = cache.get(key)
    if rate and not force:
        return rate
    try:
        btce = urllib2.urlopen(
            "https://btc-e.com/api/2/btc_usd/ticker", timeout=4).read()
        btce = json.loads(btce)
        rate = float(btce['ticker']['avg'])
        cache.set(key, rate, 60*60)  # cache for an hour
        return rate
    except:
        return None


def get_coinbase_avg_rate(force=False):
    key = 'avg_rate__coinbase'
    rate = cache.get(key)
    if rate and not force:
        return rate
    try:
        coinbase = urllib2.urlopen(
            "https://coinbase.com/api/v1/prices/buy", timeout=4).read()
        coinbase = json.loads(coinbase)
        rate = float(coinbase['total']['amount'])
        cache.set(key, rate, 60*60)  # cache for an hour
        return rate
    except:
        return None


def get_bitstamp_avg_rate(force=False):
    key = 'avg_rate__bitstamp'
    rate = cache.get(key)
    if rate and not force:
        return rate
    try:
        bitstamp = urllib2.urlopen(
            "https://www.bitstamp.net/api/ticker/", timeout=4).read()
        bitstamp = json.loads(bitstamp)
        rate = int((float(bitstamp['high'])+float(bitstamp['low']))/2.0)
        cache.set(key, rate, 60*60)  # cache for an hour
        return rate
    except:
        return None

def get_est_fee(force=False):
    key = 'est_fee'
    fee = cache.get(key)
    if not fee or force:
        fee = BITCOIND.estimatesmartfee(6*24)['feerate']
        fee = round(fee/3, 8)
        cache.set(key, fee, 60*60)
    return fee

core/forms.py
# -*- coding: utf-8 -*-
from django import forms
from core.models import *
import re
from django.utils.translation import ugettext as _
from django.utils.translation import ugettext_lazy as _l
from django.conf import settings

CURRENCIES = (('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'))
TARGET_LANGUAGES = settings.LANGUAGES
DIVIDE_BY = (("1", "1"), ("2", "2"), ("5", "5"), ("10", "10"),
             ("25", "25"), ("50", "50"), ("100", "100"))
QUANTITY = (("5", "5"), ("10", "10"), ("20", "20"), ("30", "30"))
PRICE = (("0", "0%"), ("5", "5%"),  ("10", "10%"))
TEMPLATES = (('001-original', _l('Original')),)
EXPIRATIONS = (("30", "30 days"), ("90", "3 months"),
                   ("180", "6 months"), ("365", "1 year"))

def prim():
    return _l('Nice Label')+', 0.0001 BTC'

class TipForm(forms.Form):
    bcaddr = forms.CharField(max_length=90, required=True, label=_("Send to"), widget=forms.TextInput(
        attrs={'size': '90', 'placeholder': _l('Enter bitcoin address here'), 'style': 'border:1px solid red'}))
    bcamount = forms.CharField(required=False, help_text="all at the moment", widget=forms.TextInput(
        attrs={'readonly': 'readonly', 'class': 'disabled'}))

    def clean_bcaddr(self):
        bcaddr = self.cleaned_data['bcaddr']
        if len(bcaddr) < 30:
            raise forms.ValidationError(_('Your address seems too short'))
        if not re.match("^[A-Za-z0-9_-]*$", bcaddr):
            raise forms.ValidationError(_('Must be a valid Bitcoin Address'))
        valid = BITCOIND.validateaddress(bcaddr)['isvalid']
        if not valid:
            raise forms.ValidationError(_('Must be a valid Bitcoin Address'))
        return bcaddr


class WalletForm(forms.Form):
    bcaddr_from = forms.CharField(max_length=34, required=True, label=_(
        "Your Address"), widget=forms.TextInput)  # (attrs={'size':'34', 'style':'width:240px'})
    divide_currency = forms.ChoiceField(
        choices=CURRENCIES, widget=forms.Select())
    #target_language = forms.ChoiceField(choices=TARGET_LANGUAGES)
    divide_by = forms.ChoiceField(
        widget=forms.Select, choices=DIVIDE_BY, initial=2)
    quantity = forms.ChoiceField(widget=forms.Select, choices=QUANTITY)
    price = forms.ChoiceField(widget=forms.Select, choices=PRICE)
    message = forms.CharField(max_length=40, required=False, label=_(
        "Custom message"), widget=forms.TextInput(attrs={'size': '40'}))
    template = forms.ChoiceField(widget=forms.Select, choices=TEMPLATES)
    hashtag = forms.CharField(max_length=40, required=False)
    # p&p
    print_and_post = forms.BooleanField(required=False)
    address1 = forms.CharField(max_length=32, required=False)
    address2 = forms.CharField(max_length=32, required=False)
    city = forms.CharField(max_length=24, required=False)
    state = forms.CharField(max_length=24, initial='CA', required=False)
    country = forms.CharField(max_length=24, initial="USA", required=False,
                              widget=forms.TextInput(attrs={
                                  'readonly': 'readonly',
                                  'class': 'disabled'}))
    postal_code = forms.CharField(max_length=12, required=False)
    email = forms.CharField(max_length=64, required=False)
    expiration = forms.ChoiceField(
        widget=forms.Select, choices=EXPIRATIONS, initial="30")

    def clean_bcaddr_from(self):
        bcaddr_from = self.cleaned_data['bcaddr_from']
        if len(bcaddr_from) < 32:
            raise forms.ValidationError(_('Your address seems too short'))
        if not re.match("^[A-Za-z0-9_-]*$", bcaddr_from):
            raise forms.ValidationError(_('Must be a valid Bitcoin Address'))
        try:
            valid = BITCOIND.validateaddress(bcaddr_from)['isvalid']
        except:
            raise forms.ValidationError(_('Must be a valid Bitcoin Address'))
        if not valid:
            raise forms.ValidationError(_('Must be a valid Bitcoin Address'))
        return bcaddr_from

    def clean_divide_by(self):
        d = self.cleaned_data['divide_by']
        # d check if in DIVIDE_BY
        d = Decimal(d)
        return d

    def clean_quantity(self):
        return int(self.cleaned_data['quantity'])

    def clean_price(self):
        return Decimal(self.cleaned_data['price'])

    def clean_template(self):
        return self.cleaned_data['template']+'.odt'

    def clean_expiration(self):
        return int(self.cleaned_data['expiration'])

core/templates/index.html
{% extends "base.html" %}{% load i18n %}
{% block nav_main %}active{%endblock%}
{% block content %}

<h1>What are Bitcoin.com Tips?</h1>

<p id="intro-info">
  Create tips to give Bitcoin Cash (BCH) by email or printable tickets. Recipients redeem tips by visiting a web page with instructions <a href="{% url "tips_example" %}">(example)</a>.
</p>
<p>
  
</p>

<div class="row"> 
  <div class="col-md-4">
    <div class="card mb-3">
      <div class="card-header faq-header">
        <h3>Customize</h3>
      </div>
      <div class="card-block">
        <p>{% trans "Set your message and amount." %}</p>           
      </div>
    </div>
  </div>
  
  <div class="col-md-4">
    <div class="card mb-3">
      <div class="card-header faq-header"> 
        <h3>Use Crypto as Cash</h3>
      </div>
      <div class="card-block">        
        <p>Proof of work for appreciation.</p>         
      </div>
    </div>
  </div>
  
  <div class="col-md-4">
    <div class="card mb-3">
      <div class="card-header faq-header">
        <h3>Follow Up</h3>
      </div>
      <div class="card-block">    
        <p>{% trans "Know when your tips are redeemed." %}</p>           
      </div>
    </div>
  </div>
</div>

<center>
    <h1 style="color:#fab915;">Unclaimed tips are automatically returned!</h1>        
  
    <a class="btn btn-primary" href="{% url "new" %}">Get Started</a>

    <br><br>
 
    <a href="https://bitcoincash.org/" target="_blank">What is Bitcoin Cash?</a>

    <br><br>
  
    Contact: <a href="mailto:tips-support@bitcoin.com">tips-support@bitcoin.com</a>
  </center>

{% endblock %}

core/templates/not_enough.html
{% extends "base.html" %}{%load i18n%}

{% block content %}
<link href="/static/css/semantic-full.css" rel="stylesheet" />
<script src="/static/js/semantic-full.min.js"></script>

<h1 class="ui header">{% trans "Error" %}</h1>
<div class="ui large message">
{% trans "Not enough confirmations (1 confirmation required) or not enough funds" %}.
<br/>
{% trans "Please wait about 10 minutes and try again" %}.
</div>
<br/>
<a class="ui bch-gold button" href="./">{% trans "Try again" %}</a>

{% endblock %}

core/templates/not_yet.html
{% extends "base.html" %}{%load i18n%}

{% block content %}

<h1 class="ui header">{% trans "Error" %}</h1>
<div class="ui large message">Template has not been generated yet, please try again in 5 minutes.<br/>
Result={{result}}, Info={{info}}</div>
<br/>
<a href="../" class="ui blue button">{% trans "Try again" %}</a>

{% endblock %}

core/templates/wallet-new.html
{% extends "base.html" %}{% load i18n %}{% load l10n %}

{% block content %}

{% trans "Current" %} {% trans "rate" %} (Bitstamp): ${{wallet.rate|floatformat:"2"}}
<br/><br/>

<form action="" method="post" class="ui large form">{% csrf_token %}
{{ form.non_field_errors }}

  <div class="required field">
    <label>{% trans "Your Bitcoin address" %}</label>
    {% trans "All the unused funds will be returned to this address after expiration" %}<br/>
    {{ form.bcaddr_from }}
    {{ form.bcaddr_from.errors }}
  </div>

<br/>

<div class="ui stackable three column grid">
<div class="column">
  <div class="ui two column grid">
  <div class="column">
  <div class="field"><label>{% trans "Tip Value" %}</label>
      {{ form.divide_currency.errors }}
      {{ form.divide_currency }}<br/>
      {{ form.divide_by.errors }}
      {{ form.divide_by }}</div>
  </div><div class="column">
  <div class="field"><label>{% trans "How many" %}</label>
      {{ form.quantity.errors }}
      {{ form.quantity }}</div>
  </div>
  </div>
  <br/>
  <div class="field"><label>{% trans "Expiration" %}</label>
   {{ form.expiration.errors }}
   {{ form.expiration }}
  </div>
  <br/>
  <div class="field"><label>{% trans "Template" %}</label>
    {{ form.template.errors }}
    {{ form.template }}
    {% if not custom_saveatpurse %}
    <div class="ui small label hidden nice_label">{% trans "Nice Label" %} +0.0001 BTC</div>
    {% endif %}</div>

<div class="field"><label>{% trans "Message" %}</label>
 {{ form.message.errors }}
 {{ form.message }}
 <div class="ui small label">{% trans "is printed in the center of every tip" %}</div></div>

<div class="field"><label>{% trans "Email" %}</label>
 {{ form.email.errors }}
 {{ form.email }}
<div class="ui small label">{% trans "for activation notifications" %}</div>
</div>

</div><div class="column">
  <div class="field"><label>{% trans "Donate to" %} bctip{% if request.LANGUAGE_CODE == "fi" %}ille{%endif%}</label>
    {{ form.price.errors }}
    {{ form.price }}
  </div>


<table class="ui table"><thead>
 <th>{% trans "Service" %}</th>
 <th>{% trans "Amount" %}</th>
</thead>

<tbody><tr>
 <td>{% trans "Tips" %}</td>
 <td><span id="tips_usd" style="font-weight:bold"></span></td>
</tr><tr><td>
<!--{% trans "Print and Post service" %}</td><td><span id="pap_usd" style="font-weight:bold">$0</span></td>
</tr><tr><td>-->
{% trans "Our humble tips" %}</td><td><span id="price_usd" style="font-weight:bold"></span></td>
</tr><tr><td>
{% trans "Premium Template" %}</td><td><span id="premium_extra" style="font-weight:bold">0</span></td>
</tr><tr><td>
{% trans "Transaction Fees" %}</td><td><span id="transes_btc" style="font-weight:bold">0.0 BTC</span></td>
</tr><tr>
<td colspan="2" style="text-align:right">
 <!--{% trans "Total" %} <span id="total_sign">USD</span><br/><span id="total_usd" style="font-size:150%;font-weight:bold"></span>
 <br/>-->
 {% trans "Total" %} BTC<br/><span id="total_btc" style="font-size:150%;font-weight:bold"></span>
</td>
</tr></tbody></table>





<div class="text-center"><input type="submit" class="ui fluid green button" value="{% trans "Checkout" %}" /></div>



</div><div class="center aligned column">
<div class="ui bottom pointing label">{% trans "preview" %}</div>
<img class="ui fluid bordered image" id="preview" src="/static/img/examples/tips-{{request.LANGUAGE_CODE}}-{{wallet.template|slice:":-4"}}.png" />
</div>

</div>


</form>



<!--
<h3>Optional Settings:</h3>
<div class="fieldWrapper">
    {{ form.hashtag.errors }}
    <label for="id_hashtag">Specify tag for <a href="{% url 'statistics'%}" target="_new">public leaderboard</a>:</label>
    {{ form.hashtag }} eg: #sanfrancisco, #starbucks, anything you like
</div>

<div class="fieldWrapper">
    {{ form.print_and_post.errors }}
    <label for="id_print_and_post">Print and Post Service (USA only)</label>
    {{ form.print_and_post }}
    <br>
</div>
 
<div class="row" id="post_address" style="opacity:0.5">
<div class="span3">
<p>Next day shipping from CA, USA. We print using color laser printer and 160g paper.</p>
<p>Price is $2+$1 for each 9 tips</p>
</div>

<div class="span3 offset1">
<div class="fieldWrapper">
<label for="id_address1">Address 1</label>
{{ form.address1.errors }}
{{form.address1}}
</div>

<div class="fieldWrapper">
<label for="id_address2">Address 2</label>
{{ form.address2.errors }}
{{form.address2}}
</div>

<div class="fieldWrapper">
<label for="id_city">City</label>
{{ form.city.errors }}
{{form.city}}
</div>
</div>

<div class="span3">
<div class="fieldWrapper">
<label for="id_state">State</label>
{{ form.state.errors }}
{{form.state}}
</div>

<div class="fieldWrapper">
<label for="id_country">Country</label>
{{ form.country.errors }}
{{form.country}}
</div>

<div class="fieldWrapper">
<label for="id_postal_code">ZIP</label>
{{ form.postal_code.errors }}
{{form.postal_code}}
</div>
</div>

</div> -->
    


<!--<div class="span6">
<br/>
<div class="text-center" id="happyness" style="opacity:0">
<img src="/static/img/happyness2.png" class="img-polaroid"/>
<br/> Thank you!
</div>
</div>-->

<script>{% localize off %}
var rate = {{wallet.rate}};
console.log(rate);

function recalc() {
 var cur = $('[name="divide_currency"]').val();
 $('#total_sign').html(cur)
 var cur_sign = signs[cur];
 var cur_rate = rates[cur];

 var pap_checked = $('#id_print_and_post').prop('checked');
 var premium_extra = $('[name="template"]').val();
 if (premium_extra == "005-premium" ) {
  $(".nice_label").removeClass("hidden");
 } else {
  $(".nice_label").addClass("hidden");
 }
 //var divide_by = parseInt($('input[name="divide_by"]:checked').val());
 var divide_by = parseInt($('#id_divide_by').val());
 var quantity = parseInt($('#id_quantity').val());
 var price = parseFloat($('[name=price]').val());
 var transes = quantity*{{est_fee}};
 var sum = quantity*divide_by;
 var total_usd=sum;

 $('#tips_usd').html(cur_sign+sum);
 /* -------------------- */
 if (pap_checked) {
   var pap_total = quantity/10*1+2;
   $('#pap_usd').html("$"+pap_total);
   total_usd=total_usd+pap_total;
 }
 /* -------------------- */

 if (price>0) {
  var price_usd = sum * price / 100;
  $('#price_usd').html(cur_sign+price_usd.toFixed(2));
  total_usd=total_usd+price_usd;
 } else {
  $('#price_usd').html(cur_sign+"0");
 }


 /* -------------------- */
 $('#total_usd').html(cur_sign+total_usd);
 $('#transes_btc').html(transes.toFixed(8)+" BTC");
 if (premium_extra=="005-premium") {
   $('#premium_extra').html("0.0001 BTC");
   var premium_extra = 0.0001;
 } else {
   $('#premium_extra').html("0");
   var premium_extra = 0;
 }
 var total_btc = (total_usd/rate/cur_rate+transes+premium_extra).toFixed(8);
 $('#total_btc').html(total_btc);
}

function print_and_post() {
 var pap_checked = $('#id_print_and_post').prop('checked');
 if (pap_checked) {
  alert('Sorry, Print and Post service is not available at the moment. Please vote for it.');
  $('#id_print_and_post').prop('checked','')
  //$('#post_address').css('opacity','1.0');
 } else {
  $('#post_address').css('opacity','0.4');
 }
 recalc();
}

/////////////
document_ready = function() {
 recalc();
 //$('#id_print_and_post').change(function() {
 // print_and_post();
 //});

 // $('input[name="bcaddr_from"]').change(function() {
 //  a=$('input[name="bcaddr_from"]').val();
 //  if (a.length>27) {
 //     $('#boxzero').css('background-color','#b6ffc8');
 //  } else {
 //     $('#boxzero').css('background-color','#fffbb6');
 //  }
 // });

 $('[name="divide_currency"]').change(function() {
  recalc();
 });

 $('[name="template"]').change(function() {
  recalc();
 });

 $('[name="target_language"]').change(function() {
  var lang = $('[name="target_language"]').val();
  $('#id_message').val(messages[lang]);
 });

 $('#id_divide_by').change(function() {
  recalc();
 });

 $('#id_quantity').change(function() {
  recalc();
 });

 $('[name="price"]').change(function() {
  recalc();
  var price = parseFloat($('[name=price]').val());
 });

 $('[name="template"]').change(function() {
  var p = $('[name="template"]').val();
  $("#preview").attr("src","/static/img/examples/tips-{{request.LANGUAGE_CODE}}-"+p+".png");
 });
}
$(document).ready(document_ready);
var rates = {{json_rates|safe}};
var signs = {{json_signs|safe}};
var messages = {{json_messages|safe}};
</script>{% endlocalize %}
{% endblock %}